[tool.black]
target-version = ['py36']
include = '\.pyi?$'
exclude = '''
(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.pytest_cache
    | \.tox
    | \.venv
    | fixtures
    | static
    | staticfiles
    | templates
    | migrations     # also separately exclude django migrations folder in apps
  )/
)
'''
